name: Publish app to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: npm
      - run: npm install
      - run: npm run build:prod
      - uses: actions/upload-artifact@v2
        with:
          name: output
          path: dist
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          clean: false
          path: ./dist/gh-pages
      - run: |
          cp dist/output.html dist/gh-pages/index.html
          cp dist/output.html.LICENSE.txt dist/gh-pages/index.html.LICENSE.txt
      - working-directory: ./dist/gh-pages
        run: |
          git add index.html index.html.LICENSE.txt
          revision=$(git rev-parse --short "$GITHUB_SHA")
          git config --global user.name iczero
          git config --global user.email 10750302+iczero@users.noreply.github.com
          git commit --allow-empty -m "build $revision"
          git push
